### ISSUE TITLE
NoAppException: The file/path provided (autoapp) does not appear to exist.

### ISSUE THREAD

**Issue by rsivapr** [sloria/cookiecutter-flask#104]
I've followed the README for this project but flask.cli keeps throwing me this exception when I try to run `flask`. 

```
NoAppException: The file/path provided (autoapp) does not appear to exist.  Please 
verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py
```
StackOverflow seems to think it's an issue with exporting `FLASK_APP=autoapp.py` vs `FLASK_APP=autoapp`. I've tried them both in addition to using the absolute path for the above two variations. 

Any thoughts how I can fix this?

**Comment by jordan-wright** [comment]
This happened to me when I had a circular import.

You can try to debug by opening the console on the Traceback page and running the command `__import__(app_id)`. If there's an error on the import, you'll see it there.

**Comment by gitmeister** [comment]
I had this problem just yesterday as I installed CC for the first time on my Win 7 machine. Well, like an idiot, when I cloned the project and named it... what did I name it?

"app"

Don't name it "app".

**Comment by rsivapr** [comment]
@jordan-wright  I had tried it the other day without any luck. `ImportError: No module named flask_login`. It throws an import error. But flask_login already exists. 


For instance, when I try to pip install `flask-login`, I get `Requirement already satisfied`.

**Comment by rsivapr** [comment]
@gitmeister Nope. I definitely thought this was the solution when I read your comment. That sure sounded like something I'd do. Renamed the project root directory to something else. No luck. Same issue.

**Comment by gitmeister** [comment]
@rsivapr What OS are you on? Are you running in a virtualenv? 

Here are my notes for my Windows installation:
- pip install -r requirements/dev.txt
- Ensure no spaces in paths in project
- Rename "flask.exe" in /scripts to "flask"
- set FLASK_DEBUG=1 and set FLASK_APP=autoapp.py
- cd <YOURCOOKIECUTTERDIRECTORY>
- flask run
 * Serving Flask app "autoapp"
 * Forcing debug mode on
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 309-426-538
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Dec/2016 13:20:15] "GET / HTTP/1.1" 200 -....... etc

I initially had a problem setting up my virtualenv as it wouldn't install packages in the "Lib" for the virtualenv and kept saying it found the package in cache and seemed to think it didn't need to install it so I deleted the "pip cache" in %APPDATA% and that fixed it.

**Comment by rsivapr** [comment]
Ah! Thanks!  Just for the record in this thread. I'm on ubuntu.

Issue resolved. It definitely had something to do with virtualenv. I had the virtualenv use `--system-site-packages` initially. Maybe I installed flask-login outside the env. But yes, I created a fresh virtualenv and installed requirements and viola! All good. 

Thanks all!

**Comment by nick13jaremek** [comment]
Hello there.

I was struggling with a similar issue as @rsivapr and it had me investigating a while. However, my issue was a bit more sutile:
- Also on Ubuntu, version 16.04.
- Created a fresh virtualenv, installing the dependencies specified in the requirements.txt file of the `cookie-cutter`-based Flask repo I'm working on.
- Exported the Flask env variables as stated by @gitmeister: `FLASK_APP=autoapp.py` and `FLASK_DEBUG=1`.
- Had the `autoapp.py` file located in the same directory I was within my terminal session.
- Launched flask app via the `flask run` command.
- Entered `localhost:5000` on my web browser.
- Got the following error message:
```
NoAppException: The file/path provided (autoapp) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py
```

Then I tried the following: running `python autoapp.py` to check its output. It turns out I got a quite helpful message, that pointed me out to the ultimate error:
```
ImportError: No module named requests
```

Finally, I ran `pip freeze` to confirm I did **not** have the `requests` module in the list, neither in the `requirements.txt` file. 

The solution was to add the `requests` module to the `requirements.txt` file and run `pip install` again within the proper virtualenv.

Although the issue in the end could be considered similar to @rsivapr's, I wonder why the `flask run` command does not yield a more descriptive error message. 

I hope this Github issue comments, along with this one, help other Flask users when facing a similar error.

**Comment by joshmgrant** [comment]
I had this same issue (missing dependency causing `flask run` to fail in mysterious ways). This thread definitely helped out!

**Comment by rarevalo1** [comment]
I have tried all the solutions proposed and I am still seeing this error.

**Comment by EranGoldman** [comment]
What I did was to start python shell copy paste all the imports manually and found what was the problematic import ...
This thread definitely helped out! :-)

**Comment by minhdc** [comment]
I had the same issue when starting FLASK app on cmd of Windows 8 and 8.1.
The generic solution for this case is to set the "$env:FLASK_APP" to point exactly to the location of the .py file. 
`$env:FLASK_APP = "location-of-*.py-file";
 $env:FLASK_DEBUG = 1; flask run`
If your app got bunch of modules, just point to the main one.

**Comment by githubkitchens** [comment]
If you run `flask run` and you're not in the project's root directory, you can run into this problem.
