### ISSUE TITLE
New models don't get picked up by flask-migrate

### ISSUE THREAD

**Issue by pydo** [sloria/cookiecutter-flask#149]
I'm unable to add any new models to the migrations. Here's an example model I added for testing:

The folder structure is the same as the `user` module
`{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/example/`
`__init__.py`
`models.py`

The `example/models.py` :

    from flaskapp.database import Column, Model, SurrogatePK, db

    class Example(SurrogatePK, Model):
        __tablename__ =  'examples'

I also added an import to `app.py` for whatever it's worth
`from flaskapp import commands, public, user, scraper, example`

I run `flask db init` and then `flask db migrate` but it only ever detects the `users` and `roles` models.

I've tried a variety of techniques to get new models defined, but only new models defined in `user/models.py` ever get detected when I run a migration.

Any help would be greatly appreciated. Thanks!

**Comment by pydo** [comment]
Figured out it was an import issue.
Adding `from .models import Example` to the `__init__.py` solved my problem. This allowed the `app.py` to find my models with this import `from flaskapp import example`. I still don't know how the user models gets found. They only get imported by the `forms.py` and unit tests.

**Comment by nirvana-msu** [comment]
This is indeed confusing. `User` model gets picked up by *Flask-Migrate* because it gets imported in [public/views.py](https://github.com/sloria/cookiecutter-flask/blob/16a789bf0c747d66a74e7edaf89202e3304c7271/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/public/views.py#L9), which in turn in imported in blueprint's `__init__.py`.

So it basically works by coincidence. The right solution, as you have correctly figured out, is to also import the models (and not just views) in `__init__.py` for each blueprint (this is only required for *Flask-Migrate*, nothing else). Also, rather than importing each specific model, you can import all models using:

`from .models import *`
